version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging into amazon ecr
      - aws ecr get-login-password --region region_name | docker login --username AWS --password-stdin account_id.dkr.ecr.region_name.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building docker images
      - docker build -t  web:1 .
      - docker tag web:1 account_id.dkr.ecr.us-east-1.amazonaws.com/soban:latest
      - docker tag web:1 account_id.dkr.ecr.us-east-1.amazonaws.com/soban:$CODEBUILD_BUILD_NUMBER
      
      - docker images 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushind docker images
      - docker push account_id.dkr.ecr.us-east-1.amazonaws.com/soban:latest
      - docker push account_id.dkr.ecr.us-east-1.amazonaws.com/soban:$CODEBUILD_BUILD_NUMBER
      
      - ContainerName="web1"
      - printf '[{"name":"web1","imageUri":"account_id.dkr.ecr.region_id.amazonaws.com/soban"}]' > imagedefinitions.json
      - cat imagedefinitions.json
      
artifacts:
    files:
        - imagedefinitions.json
